#!/bin/bash

# cafe (Convert All File Extensions)

# Get the file name and format
file=$1
filename=$(basename -- "$file")
extension="${filename##*.}"
filename="${filename%.*}"

# Supported formats for conversion
pandoc_formats="markdown html latex odt epub docx"
calibre_formats="pdf mobi azw3"

# usage function for the script
usage() {
    echo "Usage: file-converter [file]"
    echo "Converts a file to all supported formats using pandoc and Calibre."
    echo ""
    echo "Options:"
    echo "  file     The input file to be converted."
    echo ""
    echo "The script assumes that pandoc and Calibre are installed and available in the PATH."
    echo "If they are installed in a different location, you need to specify the correct path to the executable."
    exit 1
}

while getopts 'f:h' flag; do
  case "${flag}" in
    f) file="${OPTARG}" ;;
    h) usage
       exit 0
    ;;
    *) usage
       exit 1 
    ;;
  esac
done


# Check if pandoc and Calibre are installed
if ! command -v pandoc &> /dev/null; then
    echo "Error: pandoc is not installed. Please install pandoc and try again."
    exit 1
fi

if ! command -v ebook-convert &> /dev/null; then
    echo "Error: Calibre is not installed. Please install Calibre and try again."
    exit 1
fi

check_completion=0
# Convert file to all supported formats using pandoc
for format in $pandoc_formats; do
    pandoc "$file" -s -o "$filename.$format" && check_completion=$((check_completion+1))
done

# Convert file to all supported formats using Calibre
for format in $calibre_formats; do
    ebook-convert "$file" "$filename.$format" && check_completion=$((check_completion+1))
done

if [[ $check_completion -eq 2 ]] then
    echo "Conversion completed successfully."
else
    echo "Conversion incompleted failed to complete conversion."
fi
